# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 624)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(660, 10, 131, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 0, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 781, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 520, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(160, 190, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(160, 270, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(160, 350, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(160, 440, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(430, 190, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(430, 270, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(430, 350, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(430, 440, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(160, 30, 481, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 91, 31))
        self.label_3.setStyleSheet("font: 14pt \"Sans Serif\";")
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(90, 200, 41, 31))
        self.checkBox.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 280, 41, 31))
        self.checkBox_2.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_2.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 360, 41, 31))
        self.checkBox_3.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_3.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(90, 450, 41, 31))
        self.checkBox_4.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_4.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(670, 200, 41, 31))
        self.checkBox_5.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_5.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(670, 280, 41, 31))
        self.checkBox_6.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_6.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(670, 360, 41, 31))
        self.checkBox_7.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_7.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(670, 450, 41, 31))
        self.checkBox_8.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_8.setStyleSheet("QCheckBox::indicator {\n"
"    width:  33px;\n"
"    height: 33px;\n"
"}")
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Студент"))
        self.pushButton_9.setText(_translate("MainWindow", "Подтвердить"))
        self.label.setText(_translate("MainWindow", "Вопрос"))
        self.label_2.setText(_translate("MainWindow", "Пройдено вопросов"))
        self.pushButton_10.setText(_translate("MainWindow", "Загрузить"))
        self.label_3.setText(_translate("MainWindow", "Ошибок"))
